FROM openjdk:25-jdk
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

ENV DB_DDL_AUTO=create

ENTRYPOINT ["java","-DDB_URL=${DB_URL}", "-DDB_USERNAME=${DB_USERNAME}", "-DDB_PASSWORD=${DB_PASSWORD}", "-DDB_DDL_AUTO=${DB_DDL_AUTO}", "-DKEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}", "-DKEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}", "-DKEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME}","-DKEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}", "-DKAKAO_API_KEY=${KAKAO_API_KEY}",  "-DOPENAI_API_KEY=${OPENAI_API_KEY}", "-jar", "app.jar"]

EXPOSE 3000